name: Release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - id: install
      run: yarn install --frozen-lockfile
    - name: Set up GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: imaware-test
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - id: integration
      run: yarn test:integration
      env:
        AWS_SSM_KMS_KEY_ID: 84d61568-8bea-41aa-b2ae-efce870012fb
        AWS_REGION: us-east-1
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        GCP_PROJECT_ID: imaware-test
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      with:
        semantic_version: 17.3.7